### PR TITLE
generalize fromKeyedList

### PR DESCRIPTION
**Pull request by turboMaCk**

### CODE REVIEW

**Comment by jhrcek** [comment]
I didn't try any benchmarks, but I think that allowing multiple parents downgrades the performance guarantees.
Yes, the API will be more general, but you lose the `n * log (n)` guarantee, because then you allow the scenarios where "everything is a parent of everything" (which is already allowed by the original `fromList` API). In those cases you have potentially up to [n*(n-1)/2](https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF) `~ O(n^2)` connections between nodes. I think in such cases the linear lookup in the entire list (hidden behind the lazy nodes) is probably the better alternative compared to `O(n^2)` cost of initial construction.
On the other hand "everything is connected to everything" will probably not arise in practice, so I think it's ok to generalize the API in this way.

**Comment by turboMaCk** [comment]
My thinking is that in both cases the implementation for cases where each item has just a single parent is Just isomorphism between list and maybe (List.singleton / Just | [] / Nothing). The potential cost for this case is just a function that translates the two (`Maybe.withDefault [] << Maybe.map List.singleton`) and call of List.foldr on singleton list. For cases where items have multiple parent we expect the function to get list of parrents to be constant (the same way the function to get maybe is) so the overhead here depends on the number of parents (for each of which we need to insert item to dictionary). I believe dictionary insert is log(n) and so yeah in case that everything is children of everything else overhead of this can because significant but it seems rather transparent from the API of the function.

I've ran benchmarks before and after the change and there was some insignificant overhead.

**These are becnhamrk results after this change**

list

**These are benchmark results before the change**

maybe


Maybe worth noting that in case of Maybe API this benchmark is just extracting the value from record while in case of List api there is the additional need to translate Maybe to List.

Less important thing for design of this library is that if you want to plan to use it in GWI then you'll definitely need consider items having multiple parents because questions can belong to multiple categories (See starter category and demographic category).

Additional note is that it's always possible to define custom function for construction within the users code because this library exposes all the primitives one needs to do so.

**Comment by jhrcek** [comment]
I will no longer have a chance to use this at GWI, as this is my last day and I'm on vacation for the past week :)
But definitely thanks for merging and documenting the improvement, I think it could still come in handy for some users of the library. The expansion of sub-trees definitely wasn't the bottleneck of the intended functionality (add all from category) we were implementing, I just came across this and tried it on the pathological case.

**Comment by turboMaCk** [comment]
I see. I'll give it few more days before making final call on this. I'm honestly not sure what is the right call at the moment.

**Comment by turboMaCk** [comment]
I've decided to keep the support for multiple parents in as it seems hard to justify not supporting the use-case which seems legit.

**Pull request merged**
